In [1]:
import numpy as np

In [2]:
R=np.matrix([[-1, 0, -1, -1, -1, -1, -1, -1],
             [0, -1, 0, -1, -1, 0, -1, -1],
             [-1, 0, -1, 0, -1, -1, -1, 100],
             [-1, -1, 0, -1, -1, -1, -1, -1],
             [-1, -1, -1, -1, -1, 0, -1, -1],
             [-1, 0, -1, -1, 0, -1, 0, -1],
             [-1, -1, -1, -1, -1, 0, -1, -1],
             [-1, -1, 0, -1, -1, -1, -1, 100]])

In [3]:
R #reward matrix

matrix([[ -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [  0,  -1,   0,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,  -1,   0,  -1,  -1,  -1, 100],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,  -1,  -1,   0,  -1,   0,  -1],
        [ -1,  -1,  -1,  -1,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1, 100]])

In [4]:
R.shape

(8, 8)

In [5]:
gamma=0.8 #value for gamma

In [6]:
Q=np.matrix(np.zeros([8,8]))
Q #Q matrix

matrix([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
initial_state=0

In [8]:
def available_actions(state):
    current_state_row=R[state,]
    av_act=np.where(current_state_row>=0)[1]
    return av_act

In [9]:
available_act=available_actions(initial_state)
available_act

array([1], dtype=int64)

In [10]:
def choose_next_action(available_action_range):
    next_action=int(np.random.choice(available_act,1))
    return next_action

In [11]:
action=choose_next_action(available_act)
action

1

In [12]:
def update(current_state, gamma, action):
    global Q
    max_index=np.where(Q[action,]==np.max(Q[action,]))[1]
    if max_index.shape[0]>1:
        max_index=int(np.random.choice(max_index,1))
    else:
        max_index=int(max_index)
    max_value=Q[action,max_index]
    #Q learning formula
    Q[current_state,action]=R[current_state,action]+gamma*max_value

In [13]:
update(initial_state,gamma,action)

In [14]:
for i in range(10000):
    current_state=np.random.randint(0,int(Q.shape[0]))
    available_act=available_actions(current_state)
    action=choose_next_action(available_act)
    update(current_state,gamma,action)

In [15]:
print("Trained q matrix after 10000(iteration)")
print(Q)

Trained q matrix after 10000(iteration)
[[  0.  320.    0.    0.    0.    0.    0.    0. ]
 [256.    0.  400.    0.    0.  256.    0.    0. ]
 [  0.  320.    0.  320.    0.    0.    0.  500. ]
 [  0.    0.  400.    0.    0.    0.    0.    0. ]
 [  0.    0.    0.    0.    0.  256.    0.    0. ]
 [  0.  320.    0.    0.  204.8   0.  204.8   0. ]
 [  0.    0.    0.    0.    0.  256.    0.    0. ]
 [  0.    0.  400.    0.    0.    0.    0.  500. ]]


In [16]:
print(Q/np.max(Q)*100)

[[  0.    64.     0.     0.     0.     0.     0.     0.  ]
 [ 51.2    0.    80.     0.     0.    51.2    0.     0.  ]
 [  0.    64.     0.    64.     0.     0.     0.   100.  ]
 [  0.     0.    80.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.    51.2    0.     0.  ]
 [  0.    64.     0.     0.    40.96   0.    40.96   0.  ]
 [  0.     0.     0.     0.     0.    51.2    0.     0.  ]
 [  0.     0.    80.     0.     0.     0.     0.   100.  ]]


In [17]:
current_state=int(input("Enter the state to find path to exit:"))

Enter the state to find path to exit:3


In [18]:
goal_state=7
steps=[current_state]

In [19]:
while current_state!=goal_state:
    global steps
    next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
    
    if next_step_index.shape[0]>1:
        next_step_index=int(np.random.choice(next_Step_index,size=1))
    else:
        next_step_index=int(next_step_index)
    current_state=next_step_index
    steps.append(current_state)

In [20]:
print("Selected path:",steps)

Selected path: [3, 2, 7]
